name: Ejecutar pruebas PetStore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  karate-tests:
    runs-on: ubuntu-latest

    steps:
      - name:  Clonar el código
        uses: actions/checkout@v3

      - name:  Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name:  Ejecutar pruebas Karate
        run: mvn test -Dtest=PetTestRunner -Dkarate.options="--tags ~@e2e"

  ui-tests:
    name: Ejecutar pruebas de UI con Playwright
    runs-on: ubuntu-latest

    needs: karate-tests   # ⏳ Espera que termine el job anterior

    steps:
      - name: Clonar pruebas UI desde otro repositorio
        uses: actions/checkout@v3
        with:
          repository: guinohenostroza/petstore-ui-tests   # ✅ Reemplaza con el repo correcto
          token: ${{ secrets.GITHUB_TOKEN }}    # solo para repositorios privados
          path: ui-tests

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependencias del proyecto UI
        working-directory: ui-tests
        run: npm ci

      - name: Instalar navegadores para Playwright
        working-directory: ui-tests
        run: npx playwright install --with-deps

      - name: Ejecutar pruebas UI (Playwright + Cucumber)
        working-directory: ui-tests
        run: npm run test:ci

      - name: Subir artefactos de reporte UI
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reportes-ui
          path: ui-tests/playwright-report